const Affirmations = [
  "I am successful.",
  "I am confident.",
  "I am powerful.",
  "I am strong.",
  "I am getting better and better every day.",
  "All I need is within me right now.",
  "I wake up motivated.",
  "I am an unstoppable force of nature.",
  "I am a living, breathing example of motivation.",
  "I am living with abundance.",
  "I am having a positive and inspiring impact on the people I come into contact with.",
  "I am inspiring people through my work.",
  "I’m rising above the thoughts that are trying to make me angry or afraid.",
  "Today is a phenomenal day.",
  "I am turning DOWN the volume of negativity in my life, while simultaneously turning UP the volume of positivity.",
  "I am filled with focus.",
  "I am not pushed by my problems; I am led by my dreams.",
  "I am grateful for everything I have in my life.",
  "I am independent and self-sufficient.",
  "I can be whatever I want to be.",
  "I am not defined my by past; I am driven by my future.",
  "I use obstacles to motivate me to learn and grow.",
  "Today will be a productive day.",
  "I am intelligent and focused.",
  "I feel more grateful each day.",
  "I am getting healthier every day.",
  "Each and every day, I am getting closer to achieving my goals.",
  "Through the power of my thoughts and words, incredible transformations are happening in me and within my life right now.",
  "I am constantly growing and evolving into a better person.",
  "I’m freeing myself from all destructive doubt and fear.",
  "I accept myself for who I am and create peace, power and confidence of mind and of heart.",
  "I am going to forgive myself and free myself. I deserve to forgive and be forgiven.",
  "I am healing and strengthening every day.",
  "I’ve made it through hard times before, and I’ve come out stronger and better because of them. I’m going to make it through this.",
  "I do not waste away a single day of my life. I squeeze every ounce of value out of each of my days on this planet—today, tomorrow, and everyday.",
  "I must remember the incredible power I possess within me to achieve anything I desire.",
  "I do not engage with people who try to penetrate my mind with unhelpful thoughts and ideas—I walk away when a person or a situation isn’t healthy for me.",
  "I belong in this world; there are people that care about me and my worth.",
  "My past might be ugly, but I am still beautiful.",
  "I have made mistakes, but I will not let them define me.",
  "My soul radiates from the inside and warms the souls of others.",
  "I don’t compare myself to others. The only person I compare myself to is the person I was yesterday. And as long as the person I am today is even the tiniest bit better than the person I was yesterday—I’m meeting my own definition of success.",
  "I finish what matters and let go of what does not.",
  "I feed my spirit. I train my body. I focus my mind. This is my time.",
  "My life has meaning. What I do has meaning. My actions are meaningful and inspiring.",
  "What I have done today was the best I was able to do today. And for that, I am thankful.",
  "One small positive thought in the morning can change my whole day. So, today I rise with a powerful thought to set the tone and allow success to reverberate through every moment of my day.",
  "I set goals and go after them with all the determination I can muster. When I do this, my own skills and talents will take me to places that amaze me.",
  "Happiness is a choice, and today I choose to be happy.",
  "I am grateful for adversity because it allows me to grow.",
  "There is a benefit and an opportunity in every experience I have.",
  "My strength is greater than any struggle.",
  "All experiences I encounter shape me to be the highest version of myself.",
  "I am equipped with all the tools I need to walk through this experience with dignity and grace.",
  "I trust and believe that everything is always working out for my highest good.",
  "I cultivate deep courage and compassion within my mind, body, and spirit.",
  "Everything is unfolding in perfect timing. I release worry and choose to trust.",
  "I trust that the universe gives me exactly what I need at exactly the right time.",
  "I am trusting. What’s meant for me is already mine. I am exactly where I’m meant to be.",
  "My energy is not reserved for worrying. I use my energy to trust, believe, and have faith.",
  "Even when something doesn’t happen how I wanted, I know I’m on the right path.",
  "I surrender my resistance and allow the universe to give me what I need.",
  "I choose to find hopeful and optimistic ways to look at obstacles and roadblocks.",
  "I make the best and most out of everything that comes my way.",
  "When I’m feeling overwhelmed, I give myself space to stop and breathe.",
  "I have the strength and resourcefulness to handle anything that comes my way.",
  "My ability to conquer my challenges is limitless. My potential to succeed is infinite.",
  "I am unafraid to try and fail. I welcome the growth that comes from these experiences.",
  "I am able to release negative thoughts and feelings that do not serve me.",
  "I am willing to believe that things will always work out, even when they don’t feel like it.",
  "I cannot always control my external world, but I can control my reactions to it.",
  "I let go of worries that drain my energy.",
  "Instead of focusing on what’s going wrong, I focus my energy on what’s going right.",
  "External forces cannot dampen my resilient spirit.",
  "I trust my inner knowing in the face of uncertainty.",
  "I may stumble, but I never stay on the ground.",
  "I may make mistakes, but I don’t quit.",
  "I am kind and compassionate toward myself when I make a mistake.",
  "Mistakes do not equal failure.",
  "Mistakes do not define me. I am allowed the grace of imperfection.",
  "I am able to find lessons in my losses.",
  "I use failure as a stepping stone to success.",
  "All of my problems have solutions.",
  "Obstacles are the foundation of my success.",
  "I rise in the face of adversity.",
  "No matter what happens, I remain aligned with faith, trust, and love.",
  "The universe always has my back.",
  "I can do hard things.",
  "I am resilient.",
];

export default Affirmations;
